site:
  title: md2b
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://www.example.com
  start_page: md2b::index.adoc
content:
  sources:
  - url: ../
    branches: HEAD
    start_path: antora


ui:
  bundle:
    url: https://github.com/arotna/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

output:
  dir: ../docs/html

asciidoc:
  attributes:
    compName: md2b
