---
to: <%= dirName %>/modules/ROOT/nav.adoc
sh: mv <%= dirName %>/ass <%= dirName %>/modules/ROOT/pages
---

*  [Welcome]
** xref:welcome/index.adoc[Welcome]
** xref:welcome/oke_about.adoc[About OpenShift Kubernetes Engine]
** xref:welcome/legal-notice.adoc[Legal notice]
*  Release notes]
** xref:release_notes/ocp-4-4-release-notes.adoc[OpenShift Container Platform 4.4 release notes]
** xref:release_notes/versioning-policy.adoc[Versioning policy]
*  Architecture]
** xref:architecture/architecture.adoc[Product architecture]
** xref:architecture/architecture-installation.adoc[Installation and update]
** xref:architecture/control-plane.adoc[The control plane]
** xref:architecture/understanding-development.adoc[Understanding OpenShift development]
** xref:architecture/architecture-rhcos.adoc[Red Hat Enterprise Linux CoreOS]
** xref:architecture/cicd_gitops.adoc[The CI/CD methodology and practice]
** xref:architecture/admission-plug-ins.adoc[Admission plug-ins]
*  Installing]
**  [Installing on AWS]
*** xref:installing/installing_aws/installing-aws-account.adoc[Configuring an AWS account]
*** xref:installing/installing_aws/installing-aws-default.adoc[Installing a cluster quickly on AWS]
*** xref:installing/installing_aws/installing-aws-customizations.adoc[Installing a cluster on AWS with customizations]
*** xref:installing/installing_aws/installing-aws-network-customizations.adoc[Installing a cluster on AWS with network customizations]
*** xref:installing/installing_aws/installing-aws-vpc.adoc[Installing a cluster on AWS into an existing VPC]
*** xref:installing/installing_aws/installing-aws-private.adoc[Installing a private cluster on AWS]
*** xref:installing/installing_aws/installing-aws-user-infra.adoc[Installing a cluster on AWS using CloudFormation templates]
*** xref:installing/installing_aws/installing-restricted-networks-aws.adoc[Installing a cluster on AWS in a restricted network]
*** xref:installing/installing_aws/uninstalling-cluster-aws.adoc[Uninstalling a cluster on AWS]
**  [Installing on Azure]
*** xref:installing/installing_azure/installing-azure-account.adoc[Configuring an Azure account]
*** xref:installing/installing_azure/installing-azure-default.adoc[Installing a cluster quickly on Azure]
*** xref:installing/installing_azure/installing-azure-customizations.adoc[Installing a cluster on Azure with customizations]
*** xref:installing/installing_azure/installing-azure-network-customizations.adoc[Installing a cluster on Azure with network customizations]
*** xref:installing/installing_azure/installing-azure-vnet.adoc[Installing a cluster on Azure into an existing VNet]
*** xref:installing/installing_azure/installing-azure-private.adoc[Installing a private cluster on Azure]
*** xref:installing/installing_azure/installing-azure-user-infra.adoc[Installing a cluster on Azure using ARM templates]
*** xref:installing/installing_azure/uninstalling-cluster-azure.adoc[Uninstalling a cluster on Azure]
**  [Installing on GCP]
*** xref:installing/installing_gcp/installing-gcp-account.adoc[Configuring a GCP project]
*** xref:installing/installing_gcp/installing-gcp-default.adoc[Installing a cluster quickly on GCP]
*** xref:installing/installing_gcp/installing-gcp-customizations.adoc[Installing a cluster on GCP with customizations]
*** xref:installing/installing_gcp/installing-gcp-network-customizations.adoc[Installing a cluster on GCP with network customizations]
*** xref:installing/installing_gcp/installing-gcp-vpc.adoc[Installing a cluster on GCP into an existing VPC]
*** xref:installing/installing_gcp/installing-gcp-private.adoc[Installing a private cluster on GCP]
*** xref:installing/installing_gcp/installing-gcp-user-infra.adoc[Installing a cluster on GCP using Deployment Manager templates]
*** xref:installing/installing_gcp/installing-restricted-networks-gcp.adoc[Restricted network GCP installation]
*** xref:installing/installing_gcp/uninstalling-cluster-gcp.adoc[Uninstalling a cluster on GCP]
**  [Installing on bare metal]
*** xref:installing/installing_bare_metal/installing-bare-metal.adoc[Installing a cluster on bare metal]
*** xref:installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc[Installing a cluster on bare metal with network customizations]
*** xref:installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc[Restricted network bare metal installation]
**  [Installing on IBM Z and LinuxONE]
*** xref:installing/installing_ibm_z/installing-ibm-z.adoc[Installing a cluster on IBM Z and LinuxONE]
*** xref:installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc[Restricted network IBM Z installation]
**  [Installing on IBM Power]
*** xref:installing/installing_ibm_power/installing-ibm-power.adoc[Installing a cluster on IBM Power]
*** xref:installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc[Restricted network IBM Power installation]
**  [Installing on OpenStack]
*** xref:installing/installing_openstack/installing-openstack-installer-custom.adoc[Installing a cluster on OpenStack with customizations]
*** xref:installing/installing_openstack/installing-openstack-installer-kuryr.adoc[Installing a cluster on OpenStack with Kuryr]
*** xref:installing/installing_openstack/installing-openstack-user.adoc[Installing a cluster on OpenStack on your own infrastructure]
*** xref:installing/installing_openstack/installing-openstack-user-kuryr.adoc[Installing a cluster on OpenStack with Kuryr on your own infrastructure]
*** xref:installing/installing_openstack/uninstalling-cluster-openstack.adoc[Uninstalling a cluster on OpenStack]
*** xref:installing/installing_openstack/uninstalling-openstack-user.adoc[Uninstalling a cluster on OpenStack from your own infrastructure]
**  [Installing on RHV]
*** xref:installing/installing_rhv/installing-rhv-default.adoc[Installing a cluster quickly on RHV]
*** xref:installing/installing_rhv/installing-rhv-customizations.adoc[Installing a cluster on RHV with customizations]
*** xref:installing/installing_rhv/uninstalling-cluster-rhv.adoc[Uninstalling a cluster on RHV]
**  [Installing on vSphere]
*** xref:installing/installing_vsphere/installing-vsphere.adoc[Installing a cluster on vSphere]
*** xref:installing/installing_vsphere/installing-vsphere-network-customizations.adoc[Installing a cluster on vSphere with network customizations]
*** xref:installing/installing_vsphere/installing-restricted-networks-vsphere.adoc[Restricted network vSphere installation]
** xref:installing/installing-troubleshooting.adoc[Troubleshooting installation issues]
** xref:installing/installing-fips.adoc[Support for FIPS cryptography]
** 
[Installation configuration]
*** xref:installing/install_config/installation-types.adoc[Installation methods for different platforms]
*** xref:installing/install_config/installing-customizing.adoc[Customizing nodes]
*** xref:installing/install_config/installing-restricted-networks-preparations.adoc[Creating a mirror registry for a restricted network]
*** xref:installing/install_config/customizations.adoc[Available cluster customizations]
*** xref:installing/install_config/configuring-firewall.adoc[Configuring your firewall]
*** xref:installing/install_config/configuring-private-cluster.adoc[Configuring a private cluster]
*  Updating clusters]
** xref:updating/updating-cluster-between-minor.adoc[Updating a cluster between minor versions]
** xref:updating/updating-cluster.adoc[Updating a cluster within a minor version from the web console]
** xref:updating/updating-cluster-cli.adoc[Updating a cluster within a minor version by using the CLI]
** xref:updating/updating-cluster-rhel-compute.adoc[Updating a cluster that includes RHEL compute machines]
** xref:updating/updating-restricted-network-cluster.adoc[Updating a restricted network cluster]
*  Support]
** xref:support/getting-support.adoc[Getting support]
** xref:support/gathering-cluster-data.adoc[Gathering data about your cluster]
**  [Remote health monitoring with connected clusters]
*** xref:support/remote_health_monitoring/about-remote-health-monitoring.adoc[About remote health monitoring]
*** xref:support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring.adoc[Showing data collected by remote health monitoring]
*** xref:support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc[Opting out of remote health reporting]
*  Web console]
** xref:web_console/web-console.adoc[Accessing the web console]
** xref:web_console/using-dashboard-to-get-cluster-information.adoc[Viewing cluster information]
** xref:web_console/configuring-web-console.adoc[Configuring the web console]
** xref:web_console/customizing-the-web-console.adoc[Customizing the web console]
** xref:web_console/odc-about-developer-perspective.adoc[Developer perspective]
** xref:web_console/disabling-web-console.adoc[Disabling the web console]
*  Authentication]
** xref:authentication/understanding-authentication.adoc[Understanding authentication]
** xref:authentication/certificate-types-descriptions.adoc[Certificate types and descriptions]
** xref:authentication/configuring-internal-oauth.adoc[Configuring the internal OAuth server]
** xref:authentication/understanding-identity-provider.adoc[Understanding identity provider configuration]
**  [Configuring identity providers]
*** xref:authentication/identity_providers/configuring-htpasswd-identity-provider.adoc[Configuring an HTPasswd identity provider]
*** xref:authentication/identity_providers/configuring-keystone-identity-provider.adoc[Configuring a Keystone identity provider]
*** xref:authentication/identity_providers/configuring-ldap-identity-provider.adoc[Configuring an LDAP identity provider]
*** xref:authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc[Configuring a basic authentication identity provider]
*** xref:authentication/identity_providers/configuring-request-header-identity-provider.adoc[Configuring a request header identity provider]
*** xref:authentication/identity_providers/configuring-github-identity-provider.adoc[Configuring a GitHub or GitHub Enterprise identity provider]
*** xref:authentication/identity_providers/configuring-gitlab-identity-provider.adoc[Configuring a GitLab identity provider]
*** xref:authentication/identity_providers/configuring-google-identity-provider.adoc[Configuring a Google identity provider]
*** xref:authentication/identity_providers/configuring-oidc-identity-provider.adoc[Configuring an OpenID Connect identity provider]
**  [Configuring certificates]
*** xref:authentication/certificates/replacing-default-ingress-certificate.adoc[Replacing the default ingress certificate]
*** xref:authentication/certificates/api-server.adoc[Adding API server certificates]
*** xref:authentication/certificates/service-serving-certificate.adoc[Securing service traffic using service serving certificates]
** xref:authentication/using-rbac.adoc[Using RBAC to define and apply permissions]
** xref:authentication/remove-kubeadmin.adoc[Removing the kubeadmin user]
** xref:authentication/configuring-user-agent.adoc[Configuring the user agent]
** xref:authentication/understanding-and-creating-service-accounts.adoc[Understanding and creating service accounts]
** xref:authentication/using-service-accounts-in-applications.adoc[Using service accounts in applications]
** xref:authentication/using-service-accounts-as-oauth-client.adoc[Using a service account as an OAuth client]
** xref:authentication/tokens-scoping.adoc[Scoping tokens]
** xref:authentication/bound-service-account-tokens.adoc[Using bound service account tokens]
** xref:authentication/managing-security-context-constraints.adoc[Managing Security Context Constraints]
** xref:authentication/impersonating-system-admin.adoc[Impersonating the system:admin user]
** xref:authentication/ldap-syncing.adoc[Syncing LDAP groups]
** xref:authentication/allowing-javascript-access-api-server.adoc[Allowing JavaScript-based access to the API server from additional hosts]
** xref:authentication/encrypting-etcd.adoc[Encrypting etcd data]
*  Networking]
** xref:networking/understanding-networking.adoc[Understanding networking]
** xref:networking/accessing-hosts.adoc[Accessing hosts]
** xref:networking/cluster-network-operator.adoc[Understanding the Cluster Network Operator]
** xref:networking/dns-operator.adoc[Understanding the DNS Operator]
** xref:networking/ingress-operator.adoc[Understanding the Ingress Operator]
** xref:networking/configuring-networkpolicy.adoc[Configuring network policy]
** xref:networking/using-sctp.adoc[Using SCTP]
**  [Multiple networks]
*** xref:networking/multiple_networks/understanding-multiple-networks.adoc[Understanding multiple networks]
*** xref:networking/multiple_networks/attaching-pod.adoc[Attaching a Pod to an additional network]
*** xref:networking/multiple_networks/removing-pod.adoc[Removing a Pod from an additional network]
*** xref:networking/multiple_networks/configuring-bridge.adoc[Configuring a bridge network]
*** xref:networking/multiple_networks/configuring-macvlan.adoc[Configuring a macvlan network]
*** xref:networking/multiple_networks/configuring-ipvlan.adoc[Configuring an ipvlan network]
*** xref:networking/multiple_networks/configuring-host-device.adoc[Configuring a host-device network]
*** xref:networking/multiple_networks/edit-additional-network.adoc[Editing an additional network]
*** xref:networking/multiple_networks/remove-additional-network.adoc[Removing an additional network]
*** xref:networking/multiple_networks/configuring-ptp.adoc[Configuring PTP]
**  [Hardware networks]
*** xref:networking/hardware_networks/about-sriov.adoc[About Single Root I/O Virtualization (SR-IOV) hardware networks]
*** xref:networking/hardware_networks/installing-sriov-operator.adoc[Installing the SR-IOV Operator]
*** xref:networking/hardware_networks/configuring-sriov-operator.adoc[Configuring the SR-IOV Operator]
*** xref:networking/hardware_networks/configuring-sriov-device.adoc[Configuring an SR-IOV network device]
*** xref:networking/hardware_networks/configuring-sriov-net-attach.adoc[Configuring an SR-IOV network attachment]
*** xref:networking/hardware_networks/add-pod.adoc[Adding Pod to an SR-IOV network]
*** xref:networking/hardware_networks/using-sriov-multicast.adoc[Using high performance multicast]
*** xref:networking/hardware_networks/using-dpdk-and-rdma.adoc[Using DPDK and RDMA]
**  [OpenShift SDN default CNI network provider]
*** xref:networking/openshift_sdn/about-openshift-sdn.adoc[About the OpenShift SDN default CNI network provider]
*** xref:networking/openshift_sdn/assigning-egress-ips.adoc[Configuring egress IPs for a project]
*** xref:networking/openshift_sdn/configuring-egress-firewall.adoc[Configuring an egress firewall for a project]
*** xref:networking/openshift_sdn/editing-egress-firewall.adoc[Editing an egress firewall for a project]
*** xref:networking/openshift_sdn/removing-egress-firewall.adoc[Removing an egress firewall from a project]
*** xref:networking/openshift_sdn/enabling-multicast.adoc[Enabling multicast for a project]
*** xref:networking/openshift_sdn/disabling-multicast.adoc[Disabling multicast for a project]
*** xref:networking/openshift_sdn/multitenant-isolation.adoc[Configuring multitenant isolation]
*** xref:networking/openshift_sdn/configuring-kube-proxy.adoc[Configuring kube-proxy]
** 
[OVN-Kubernetes default CNI network provider]
*** xref:networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc[About the OVN-Kubernetes network provider]
*** xref:networking/ovn_kubernetes_network_provider/enabling-multicast.adoc[Enabling multicast for a project]
*** xref:networking/ovn_kubernetes_network_provider/disabling-multicast.adoc[Disabling multicast for a project]
**  [Configuring Routes]
*** xref:networking/routes/route-configuration.adoc[Route configuration]
*** xref:networking/routes/secured-routes.adoc[Secured routes]
**  [Configuring ingress cluster traffic]
*** xref:networking/configuring_ingress_cluster_traffic/overview-traffic.adoc[Overview]
*** xref:networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc[Configuring ingress cluster traffic using an Ingress Controller]
*** xref:networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer.adoc[Configuring ingress cluster traffic using a load balancer]
*** xref:networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc[Configuring ingress cluster traffic using a service external IP]
*** xref:networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-nodeport.adoc[Configuring ingress cluster traffic using a NodePort]
** xref:networking/enable-cluster-wide-proxy.adoc[Configuring the cluster-wide proxy]
** xref:networking/configuring-a-custom-pki.adoc[Configuring a custom PKI]
*  Storage]
** xref:storage/understanding-persistent-storage.adoc[Understanding persistent storage]
**  [Configuring persistent storage]
*** xref:storage/persistent_storage/persistent-storage-efs.adoc[Persistent storage using Amazon EFS]
*** xref:storage/persistent_storage/persistent-storage-aws.adoc[Persistent storage using AWS Elastic Block Store]
*** xref:storage/persistent_storage/persistent-storage-azure.adoc[Persistent storage using Azure Disk]
*** xref:storage/persistent_storage/persistent-storage-azure-file.adoc[Persistent storage using Azure File]
*** xref:storage/persistent_storage/persistent-storage-cinder.adoc[Persistent storage using Cinder]
*** xref:storage/persistent_storage/persistent-storage-fibre.adoc[Persistent storage using Fibre Channel]
*** xref:storage/persistent_storage/persistent-storage-flexvolume.adoc[Persistent storage using FlexVolume]
*** xref:storage/persistent_storage/persistent-storage-gce.adoc[Persistent storage using GCE Persistent Disk]
*** xref:storage/persistent_storage/persistent-storage-hostpath.adoc[Persistent storage using hostPath]
*** xref:storage/persistent_storage/persistent-storage-iscsi.adoc[Persistent Storage using iSCSI]
*** xref:storage/persistent_storage/persistent-storage-local.adoc[Persistent storage using local volumes]
*** xref:storage/persistent_storage/persistent-storage-nfs.adoc[Persistent storage using NFS]
*** xref:storage/persistent_storage/persistent-storage-ocs.adoc[Persistent storage using Red Hat OpenShift Container Storage]
*** xref:storage/persistent_storage/persistent-storage-vsphere.adoc[Persistent storage using VMware vSphere]
**  [Using Container Storage Interface (CSI)]
*** xref:storage/container_storage_interface/persistent-storage-csi.adoc[Configuring CSI volumes]
*** xref:storage/container_storage_interface/persistent-storage-csi-snapshots.adoc[Using CSI volume snapshots]
*** xref:storage/container_storage_interface/persistent-storage-csi-cloning.adoc[Using CSI volume cloning]
** xref:storage/expanding-persistent-volumes.adoc[Expanding persistent volumes]
** xref:storage/dynamic-provisioning.adoc[Dynamic provisioning]
*  Registry]
** xref:registry/architecture-component-imageregistry.adoc[Overview]
** xref:registry/configuring-registry-operator.adoc[Image Registry Operator in Openshift Container Platform]
**  [Setting up and configuring the registry]
*** xref:registry/configuring_registry_storage/configuring-registry-storage-aws-user-infrastructure.adoc[Configuring the registry for AWS user-provisioned infrastructure]
*** xref:registry/configuring_registry_storage/configuring-registry-storage-gcp-user-infrastructure.adoc[Configuring the registry for GCP user-provisioned infrastructure]
*** xref:registry/configuring_registry_storage/configuring-registry-storage-azure-user-infrastructure.adoc[Configuring the registry for Azure user-provisioned infrastructure]
*** xref:registry/configuring_registry_storage/configuring-registry-storage-baremetal.adoc[Configuring the registry for bare metal]
*** xref:registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc[Configuring the registry for vSphere]
** xref:registry/registry-options.adoc[Registry options]
** xref:registry/accessing-the-registry.adoc[Accessing the registry]
** xref:registry/securing-exposing-registry.adoc[Exposing the registry]
*  Operators]
** xref:operators/olm-what-operators-are.adoc[Understanding Operators]
** 
[Understanding the Operator Lifecycle Manager (OLM)]
*** xref:operators/understanding_olm/olm-understanding-olm.adoc[Workflow and architecture]
*** xref:operators/understanding_olm/olm-understanding-dependency-resolution.adoc[Dependency resolution]
*** xref:operators/understanding_olm/olm-understanding-operatorgroups.adoc[OperatorGroups]
** xref:operators/olm-understanding-operatorhub.adoc[Understanding the OperatorHub]
** xref:operators/olm-adding-operators-to-cluster.adoc[Adding Operators to a cluster]
** xref:operators/olm-configuring-proxy-support.adoc[Configuring proxy support]
** xref:operators/olm-deleting-operators-from-cluster.adoc[Deleting Operators from a cluster]
** xref:operators/olm-creating-apps-from-installed-operators.adoc[Creating applications from installed Operators]
** xref:operators/olm-status.adoc[Viewing Operator status]
** xref:operators/olm-creating-policy.adoc[Creating policy for Operator installations and upgrades]
** xref:operators/olm-restricted-networks.adoc[Using OLM on restricted networks]
**  [CRDs]
*** xref:operators/crds/crd-extending-api-with-crds.adoc[Extending the Kubernetes API with CRDs]
*** xref:operators/crds/crd-managing-resources-from-crds.adoc[Managing resources from CRDs]
**  [Operator SDK]
*** xref:operators/operator_sdk/osdk-getting-started.adoc[Getting started with the Operator SDK]
*** xref:operators/operator_sdk/osdk-ansible.adoc[Creating Ansible-based Operators]
*** xref:operators/operator_sdk/osdk-helm.adoc[Creating Helm-based Operators]
*** xref:operators/operator_sdk/osdk-generating-csvs.adoc[Generating a ClusterServiceVersion (CSV)]
*** xref:operators/operator_sdk/osdk-scorecard.adoc[Validating Operators using the scorecard]
*** xref:operators/operator_sdk/osdk-monitoring-prometheus.adoc[Configuring built-in monitoring with Prometheus]
*** xref:operators/operator_sdk/osdk-leader-election.adoc[Configuring leader election]
*** xref:operators/operator_sdk/osdk-cli-reference.adoc[Operator SDK CLI reference]
*** xref:operators/operator_sdk/osdk-appendices.adoc[Appendices]
** xref:operators/operator-reference.adoc[Red Hat Operators]
*  Builds]
** xref:builds/understanding-image-builds.adoc[Understanding image builds]
** xref:builds/understanding-buildconfigs.adoc[Understanding build configurations]
** xref:builds/creating-build-inputs.adoc[Creating build inputs]
** xref:builds/managing-build-output.adoc[Managing build output]
** xref:builds/build-strategies.adoc[Using build strategies]
** xref:builds/custom-builds-buildah.adoc[Custom image builds with Buildah]
** xref:builds/basic-build-operations.adoc[Performing basic builds]
** xref:builds/triggering-builds-build-hooks.adoc[Triggering and modifying builds]
** xref:builds/advanced-build-operations.adoc[Performing advanced builds]
** xref:builds/running-entitled-builds.adoc[Using Red Hat subscriptions in builds]
** xref:builds/securing-builds-by-strategy.adoc[Securing builds by strategy]
** xref:builds/build-configuration.adoc[Build configuration resources]
** xref:builds/troubleshooting-builds.adoc[Troubleshooting builds]
** xref:builds/setting-up-trusted-ca.adoc[Setting up additional trusted certificate authorities for builds]
*  Pipelines]
** xref:pipelines/understanding-openshift-pipelines.adoc[Understanding OpenShift Pipelines]
** xref:pipelines/installing-pipelines.adoc[Installing OpenShift Pipelines]
** xref:pipelines/uninstalling-pipelines.adoc[Uninstalling OpenShift Pipelines]
** xref:pipelines/creating-applications-with-cicd-pipelines.adoc[Creating applications with OpenShift Pipelines]
** xref:pipelines/working-with-pipelines-using-the-developer-perspective.adoc[Working with Pipelines using the Developer perspective]
** xref:pipelines/op-release-notes.adoc[OpenShift Pipelines release notes]
*  Images]
** xref:openshift_images/configuring-samples-operator.adoc[Configuring the Samples Operator]
** xref:openshift_images/samples-operator-alt-registry.adoc[Using the Samples Operator with an alternate registry]
** xref:openshift_images/images-understand.adoc[Understanding containers, images, and imagestreams]
** xref:openshift_images/create-images.adoc[Creating images]
**  [Managing images]
*** xref:openshift_images/managing_images/managing-images-overview.adoc[Managing images overview]
*** xref:openshift_images/managing_images/tagging-images.adoc[Tagging images]
*** xref:openshift_images/managing_images/image-pull-policy.adoc[Image pull policy]
*** xref:openshift_images/managing_images/using-image-pull-secrets.adoc[Using image pull secrets]
** xref:openshift_images/image-streams-manage.adoc[Managing imagestreams]
** xref:openshift_images/image-configuration.adoc[Image configuration resources]
** xref:openshift_images/using-templates.adoc[Using templates]
** xref:openshift_images/templates-using-ruby-on-rails.adoc[Using Ruby on Rails]
**  [Using images]
*** xref:openshift_images/using_images/using-images-overview.adoc[Using images overview]
*** xref:openshift_images/using_images/images-other-jenkins.adoc[Configuring Jenkins images]
*** xref:openshift_images/using_images/images-other-jenkins-agent.adoc[Jenkins agent]
*  Applications]
**  [Projects]
*** xref:applications/projects/working-with-projects.adoc[Working with projects]
*** xref:applications/projects/creating-project-other-user.adoc[Creating a project as another user]
*** xref:applications/projects/configuring-project-creation.adoc[Configuring project creation]
**  [Application life cycle management]
*** xref:applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc[Creating applications using the Developer perspective]
*** xref:applications/application_life_cycle_management/creating-apps-from-installed-operators.adoc[Creating applications from installed Operators]
*** xref:applications/application_life_cycle_management/creating-applications-using-cli.adoc[Creating applications using the CLI]
*** xref:applications/application_life_cycle_management/odc-viewing-application-composition-using-topology-view.adoc[Viewing application composition using the Topology view]
*** xref:applications/application_life_cycle_management/odc-editing-applications.adoc[Editing applications]
*** xref:applications/application_life_cycle_management/odc-working-with-helm-charts-using-developer-perspective.adoc[Working with Helm charts using the Developer perspective]
*** xref:applications/application_life_cycle_management/odc-deleting-applications.adoc[Deleting applications]
**  [Service brokers]
*** xref:applications/service_brokers/installing-service-catalog.adoc[Installing Service Catalog]
*** xref:applications/service_brokers/uninstalling-service-catalog.adoc[Uninstalling Service Catalog]
*** xref:applications/service_brokers/installing-template-service-broker.adoc[Installing the Template Service Broker]
*** xref:applications/service_brokers/uninstalling-template-service-broker.adoc[Uninstalling the Template Service Broker]
** 
[Deployments]
*** xref:applications/deployments/what-deployments-are.adoc[Understanding Deployments and DeploymentConfigs]
*** xref:applications/deployments/managing-deployment-processes.adoc[Managing deployment processes]
*** xref:applications/deployments/deployment-strategies.adoc[Using DeploymentConfig strategies]
*** xref:applications/deployments/route-based-deployment-strategies.adoc[Using route-based deployment strategies]
**  [Quotas]
*** xref:applications/quotas/quotas-setting-per-project.adoc[Resource quotas per project]
*** xref:applications/quotas/quotas-setting-across-multiple-projects.adoc[Resource quotas across multiple projects]
** xref:applications/odc-monitoring-project-and-application-metrics-using-developer-perspective.adoc[Monitoring project and application metrics using the Developer perspective]
** xref:applications/application-health.adoc[Monitoring application health]
** xref:applications/idling-applications.adoc[Idling applications]
** xref:applications/pruning-objects.adoc[Pruning objects to reclaim resources]
** xref:applications/red-hat-marketplace.adoc[Using the Red Hat Marketplace]
*  Machine management]
**  [Creating MachineSets]
*** xref:machine_management/creating_machinesets/creating-machineset-aws.adoc[Creating a MachineSet on AWS]
*** xref:machine_management/creating_machinesets/creating-machineset-azure.adoc[Creating a MachineSet on Azure]
*** xref:machine_management/creating_machinesets/creating-machineset-gcp.adoc[Creating a MachineSet on GCP]
** xref:machine_management/manually-scaling-machineset.adoc[Manually scaling a MachineSet]
** xref:machine_management/modifying-machineset.adoc[Modifying a MachineSet]
** xref:machine_management/deleting-machine.adoc[Deleting a Machine]
** xref:machine_management/applying-autoscaling.adoc[Applying autoscaling to a cluster]
** xref:machine_management/creating-infrastructure-machinesets.adoc[Creating infrastructure MachineSets]
** xref:machine_management/adding-rhel-compute.adoc[Adding a RHEL compute machine]
** xref:machine_management/more-rhel-compute.adoc[Adding more RHEL compute machines]
** xref:machine_management/deploying-machine-health-checks.adoc[Deploying machine health checks]
*  Nodes]
**  [Working with pods]
*** xref:nodes/pods/nodes-pods-using.adoc[About Pods]
*** xref:nodes/pods/nodes-pods-viewing.adoc[Viewing Pods]
*** xref:nodes/pods/nodes-pods-configuring.adoc[Configuring a cluster for Pods]
*** xref:nodes/pods/nodes-pods-autoscaling.adoc[Automatically scaling pods]
*** xref:nodes/pods/nodes-pods-secrets.adoc[Providing sensitive data to Pods]
*** xref:nodes/pods/nodes-pods-plugins.adoc[Using Device Manager to make devices available to nodes]
*** xref:nodes/pods/nodes-pods-priority.adoc[Including pod priority in Pod scheduling decisions]
*** xref:nodes/pods/nodes-pods-node-selectors.adoc[Placing pods on specific nodes using node selectors]
**  [Controlling pod placement onto nodes (scheduling)]
*** xref:nodes/scheduling/nodes-scheduler-about.adoc[About pod placement using the scheduler]
*** xref:nodes/scheduling/nodes-scheduler-default.adoc[Configuring the default scheduler to control pod placement]
*** xref:nodes/scheduling/nodes-scheduler-pod-affinity.adoc[Placing pods relative to other pods using pod affinity and anti-affinity rules]
*** xref:nodes/scheduling/nodes-scheduler-node-affinity.adoc[Controlling pod placement on nodes using node affinity rules]
*** xref:nodes/scheduling/nodes-scheduler-overcommit.adoc[Placing pods onto overcommited nodes]
*** xref:nodes/scheduling/nodes-scheduler-taints-tolerations.adoc[Controlling pod placement using node taints]
*** xref:nodes/scheduling/nodes-scheduler-node-selectors.adoc[Placing pods on specific nodes using node selectors]
*** xref:nodes/scheduling/nodes-descheduler.adoc[Evicting pods using the descheduler]
**  [Using Jobs and DaemonSets]
*** xref:nodes/jobs/nodes-pods-daemonsets.adoc[Running background tasks on nodes automatically with daemonsets]
*** xref:nodes/jobs/nodes-nodes-jobs.adoc[Running tasks in pods using jobs]
**  [Working with nodes]
*** xref:nodes/nodes/nodes-nodes-viewing.adoc[Viewing and listing the nodes in your cluster]
*** xref:nodes/nodes/nodes-nodes-working.adoc[Working with nodes]
*** xref:nodes/nodes/nodes-nodes-managing.adoc[Managing Nodes]
*** xref:nodes/nodes/nodes-nodes-managing-max-pods.adoc[Managing the maximum number of Pods per Node]
*** xref:nodes/nodes/nodes-node-tuning-operator.adoc[Using the Node Tuning Operator]
*** xref:nodes/nodes/nodes-nodes-rebooting.adoc[Understanding node rebooting]
*** xref:nodes/nodes/nodes-nodes-garbage-collection.adoc[Freeing node resources using garbage collection]
*** xref:nodes/nodes/nodes-nodes-resources-configuring.adoc[Allocating resources for nodes]
*** xref:nodes/nodes/nodes-nodes-audit-log.adoc[Viewing node audit logs]
*** xref:nodes/nodes/nodes-nodes-machine-config-daemon-metrics.adoc[Machine Config Daemon metrics]
**  [Working with containers]
*** xref:nodes/containers/nodes-containers-using.adoc[Using containers]
*** xref:nodes/containers/nodes-containers-init.adoc[Using Init Containers to perform tasks before a pod is deployed]
*** xref:nodes/containers/nodes-containers-volumes.adoc[Using volumes to persist container data]
*** xref:nodes/containers/nodes-containers-projected-volumes.adoc[Mapping volumes using projected volumes]
*** xref:nodes/containers/nodes-containers-downward-api.adoc[Allowing containers to consume API objects]
*** xref:nodes/containers/nodes-containers-copying-files.adoc[Copying files to or from a container]
*** xref:nodes/containers/nodes-containers-remote-commands.adoc[Executing remote commands in a container]
*** xref:nodes/containers/nodes-containers-port-forwarding.adoc[Using port forwarding to access applications in a container]
*** xref:nodes/containers/nodes-containers-sysctls.adoc[Using sysctls in containers]
**  [Working with clusters]
*** xref:nodes/clusters/nodes-containers-events.adoc[Viewing system event information in a cluster]
*** xref:nodes/clusters/nodes-cluster-resource-levels.adoc[Analyzing cluster resource levels]
*** xref:nodes/clusters/nodes-cluster-resource-configure.adoc[Configuring cluster memory to meet container memory and risk requirements]
*** xref:nodes/clusters/nodes-cluster-overcommit.adoc[Configuring your cluster to place pods on overcommited nodes]
*** xref:nodes/clusters/nodes-cluster-enabling-features.adoc[Enabling features using FeatureGates]
*  Logging]
** xref:logging/cluster-logging.adoc[About cluster logging]
** xref:logging/cluster-logging-deploying-about.adoc[About deploying cluster logging]
** xref:logging/cluster-logging-deploying.adoc[Deploying cluster logging]
** xref:logging/cluster-logging-upgrading.adoc[Updating cluster logging]
** xref:logging/cluster-logging-eventrouter.adoc[Deploying and Configuring the Event Router]
** xref:logging/cluster-logging-viewing.adoc[Viewing cluster logs]
** xref:logging/cluster-logging-kibana-interface.adoc[Viewing cluster logs using Kibana]
**  [Configuring your cluster logging deployment]
*** xref:logging/config/cluster-logging-configuring-about.adoc[About configuring cluster logging]
*** xref:logging/config/cluster-logging-management.adoc[Changing cluster logging management state]
*** xref:logging/config/cluster-logging-configuring.adoc[Configuring cluster logging]
*** xref:logging/config/cluster-logging-elasticsearch.adoc[Configuring Elasticsearch]
*** xref:logging/config/cluster-logging-kibana.adoc[Configuring Kibana]
*** xref:logging/config/cluster-logging-curator.adoc[Configuring Curator]
*** xref:logging/config/cluster-logging-collector.adoc[Configuring the logging collector]
*** xref:logging/config/cluster-logging-tolerations.adoc[Using tolerations to control cluster logging pod placement]
*** xref:logging/config/cluster-logging-external.adoc[Forward logs to third party systems]
*** xref:logging/config/cluster-logging-systemd.adoc[Configuring systemd-journald for cluster logging]
** xref:logging/cluster-logging-elasticsearch-status.adoc[Viewing Elasticsearch status]
** xref:logging/cluster-logging-cluster-status.adoc[Viewing cluster logging status]
** xref:logging/cluster-logging-moving-nodes.adoc[Moving the cluster logging resources with node selectors]
** xref:logging/cluster-logging-manual-rollout.adoc[Manually rolling out Elasticsearch]
** xref:logging/cluster-logging-troubleshooting.adoc[Troubleshooting Kibana]
** xref:logging/cluster-logging-exported-fields.adoc[Exported fields]
** xref:logging/cluster-logging-uninstall.adoc[Uninstalling cluster logging]
*  Monitoring]
**  [Cluster monitoring]
*** xref:monitoring/cluster_monitoring/about-cluster-monitoring.adoc[About cluster monitoring]
*** xref:monitoring/cluster_monitoring/configuring-the-monitoring-stack.adoc[Configuring the monitoring stack]
*** xref:monitoring/cluster_monitoring/managing-cluster-alerts.adoc[Managing cluster alerts]
*** xref:monitoring/cluster_monitoring/examining-cluster-metrics.adoc[Examining cluster metrics]
*** xref:monitoring/cluster_monitoring/prometheus-alertmanager-and-grafana.adoc[Accessing Prometheus, Alertmanager, and Grafana]
** xref:monitoring/monitoring-your-own-services.adoc[Monitoring your own services]
** xref:monitoring/exposing-custom-application-metrics-for-autoscaling.adoc[Exposing custom application metrics for autoscaling]
*  Metering]
** xref:metering/metering-about-metering.adoc[About metering]
** xref:metering/metering-installing-metering.adoc[Installing metering]
**  [Configuring metering]
*** xref:metering/configuring_metering/metering-about-configuring.adoc[About configuring metering]
*** xref:metering/configuring_metering/metering-common-config-options.adoc[Common configuration options]
*** xref:metering/configuring_metering/metering-configure-persistent-storage.adoc[Configuring persistent storage]
*** xref:metering/configuring_metering/metering-configure-hive-metastore.adoc[Configuring the Hive metastore]
*** xref:metering/configuring_metering/metering-configure-reporting-operator.adoc[Configuring the reporting operator]
*** xref:metering/configuring_metering/metering-configure-aws-billing-correlation.adoc[Configuring AWS billing correlation]
**  [Reports]
*** xref:metering/reports/metering-about-reports.adoc[About reports]
*** xref:metering/reports/metering-storage-locations.adoc[Storage Locations]
** xref:metering/metering-using-metering.adoc[Using metering]
** xref:metering/metering-usage-examples.adoc[Examples of using metering]
** xref:metering/metering-troubleshooting-debugging.adoc[Troubleshooting and debugging]
** xref:metering/metering-uninstall.adoc[Uninstalling metering]
*  Scalability and performance]
** xref:scalability_and_performance/recommended-install-practices.adoc[Recommended installation practices]
** xref:scalability_and_performance/recommended-host-practices.adoc[Recommended host practices]
** xref:scalability_and_performance/recommended-cluster-scaling-practices.adoc[Recommended cluster scaling practices]
** xref:scalability_and_performance/using-node-tuning-operator.adoc[Using the Node Tuning Operator]
** xref:scalability_and_performance/using-cluster-loader.adoc[Using Cluster Loader]
** xref:scalability_and_performance/using-cpu-manager.adoc[Using CPU Manager]
** xref:scalability_and_performance/using-topology-manager.adoc[Using Topology Manager]
** xref:scalability_and_performance/scaling-cluster-monitoring-operator.adoc[Scaling the Cluster Monitoring Operator]
** xref:scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc[Planning your environment according to object maximums]
** xref:scalability_and_performance/optimizing-storage.adoc[Optimizing storage]
** xref:scalability_and_performance/routing-optimization.adoc[Optimizing routing]
** xref:scalability_and_performance/what-huge-pages-do-and-how-they-are-consumed-by-apps.adoc[What huge pages do and how they are consumed by apps]
** xref:scalability_and_performance/argocd.adoc[Using ArgoCD]
*  Backup and restore]
** xref:backup_and_restore/backing-up-etcd.adoc[Backing up etcd data]
** xref:backup_and_restore/replacing-unhealthy-etcd-member.adoc[Replacing an unhealthy etcd member]
**  [Disaster recovery]
*** xref:backup_and_restore/disaster_recovery/about-disaster-recovery.adoc[About disaster recovery]
*** xref:backup_and_restore/disaster_recovery/scenario-1-infra-recovery.adoc[Recovering from lost master hosts]
*** xref:backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc[Restoring to a previous cluster state]
*** xref:backup_and_restore/disaster_recovery/scenario-3-expired-certs.adoc[Recovering from expired control plane certificates]
*  Migration]
**  [Migrating from OpenShift Container Platform 3]
*** xref:migration/migrating_3_4/about-migration.adoc[About migrating from OpenShift Container Platform 3 to 4]
*** xref:migration/migrating_3_4/planning-migration-3-to-4.adoc[Planning your migration from OpenShift Container Platform 3 to 4]
*** xref:migration/migrating_3_4/migrating-application-workloads-3-4.adoc[Migration tools and prerequisites]
*** xref:migration/migrating_3_4/deploying-cam-3-4.adoc[Deploying the Cluster Application Migration tool]
*** xref:migration/migrating_3_4/configuring-replication-repository-3-4.adoc[Configuring a replication repository]
*** xref:migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc[Migrating applications with the CAM web console]
*** xref:migration/migrating_3_4/migrating-with-cpma.adoc[Migrating control plane settings with the Control Plane Migration Assistant]
*** xref:migration/migrating_3_4/troubleshooting-3-4.adoc[Troubleshooting]
**  [Migrating from OpenShift Container Platform 4.1]
*** xref:migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc[Migration tools and prerequisites]
*** xref:migration/migrating_4_1_4/deploying-cam-4-1-4.adoc[Deploying the Cluster Application Migration tool]
*** xref:migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc[Configuring a replication repository]
*** xref:migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc[Migrating applications with the CAM web console]
*** xref:migration/migrating_4_1_4/troubleshooting-4-1-4.adoc[Troubleshooting]
**  [Migrating from Openshift Container Platform 4.2 and later]
*** xref:migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc[Migration tools and prerequisites]
*** xref:migration/migrating_4_2_4/deploying-cam-4-2-4.adoc[Deploying the Cluster Application Migration tool]
*** xref:migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc[Configuring a replication repository]
*** xref:migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc[Migrating applications with the CAM web console]
*** xref:migration/migrating_4_2_4/troubleshooting-4-2-4.adoc[Troubleshooting]
*  CLI tools]
**  [OpenShift CLI (oc)]
*** xref:cli_reference/openshift_cli/getting-started-cli.adoc[Getting started with the CLI]
*** xref:cli_reference/openshift_cli/configuring-cli.adoc[Configuring the CLI]
*** xref:cli_reference/openshift_cli/extending-cli-plugins.adoc[Extending the CLI with plug-ins]
*** xref:cli_reference/openshift_cli/developer-cli-commands.adoc[Developer CLI commands]
*** xref:cli_reference/openshift_cli/administrator-cli-commands.adoc[Administrator CLI commands]
*** xref:cli_reference/openshift_cli/usage-oc-kubectl.adoc[Usage of oc and kubectl commands]
**  [Developer CLI (odo)]
*** xref:cli_reference/developer_cli_odo/understanding-odo.adoc[Understanding odo]
*** xref:cli_reference/developer_cli_odo/odo-architecture.adoc[odo architecture]
*** xref:cli_reference/developer_cli_odo/installing-odo.adoc[Installing odo]
***  [Using odo in a restricted environment]
**** xref:cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/about-odo-in-a-restricted-environment.adoc[About odo in a restricted environment]
**** xref:cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/pushing-the-odo-init-image-to-the-restricted-cluster-registry.adoc[Pushing the odo init image to the restricted cluster registry]
**** xref:cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/creating-and-deploying-a-component-to-the-disconnected-cluster.adoc[Creating and deploying a component to the disconnected cluster]
*** xref:cli_reference/developer_cli_odo/creating-a-single-component-application-with-odo.adoc[Creating a single-component application with odo]
*** xref:cli_reference/developer_cli_odo/creating-a-multicomponent-application-with-odo.adoc[Creating a multicomponent application with odo]
*** xref:cli_reference/developer_cli_odo/creating-an-application-with-a-database.adoc[Creating an application with a database]
*** xref:cli_reference/developer_cli_odo/creating-applications-by-using-devfiles.adoc[Creating applications by using devfiles]
*** xref:cli_reference/developer_cli_odo/using-sample-applications.adoc[Using sample applications]
*** xref:cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc[Creating instances of services managed by Operators]
*** xref:cli_reference/developer_cli_odo/debugging-applications-in-odo.adoc[Debugging applications in odo]
*** xref:cli_reference/developer_cli_odo/managing-environment-variables-in-odo.adoc[Managing environment variables in odo]
*** xref:cli_reference/developer_cli_odo/configuring-the-odo-cli.adoc[Configuring the odo CLI]
*** xref:cli_reference/developer_cli_odo/odo-cli-reference.adoc[odo CLI reference]
*** xref:cli_reference/developer_cli_odo/odo-release-notes.adoc[odo release notes]
**  [Helm CLI]
*** xref:cli_reference/helm_cli/getting-started-with-helm-on-openshift-container-platform.adoc[Getting started with Helm on OpenShift Container Platform]
** xref:cli_reference/kn-cli-tools.adoc[Knative CLI (kn) for use with OpenShift Serverless]
**  [Pipelines CLI (tkn)]
*** xref:cli_reference/tkn_cli/installing-tkn.adoc[Installing tkn]
*** xref:cli_reference/tkn_cli/op-configuring-tkn.adoc[Configuring tkn]
*** xref:cli_reference/tkn_cli/op-tkn-reference.adoc[Basic tkn commands]
*  OpenShift REST APIs]
** xref:rest_api/index.adoc[API endpoints]
*  Service Mesh]
** xref:service_mesh/servicemesh-release-notes.adoc[Service Mesh release notes]
**  [Service Mesh architecture]
*** xref:service_mesh/service_mesh_arch/understanding-ossm.adoc[Understanding Service Mesh]
*** xref:service_mesh/service_mesh_arch/ossm-kiali.adoc[Understanding Kiali]
*** xref:service_mesh/service_mesh_arch/ossm-jaeger.adoc[Understanding Jaeger]
*** xref:service_mesh/service_mesh_arch/ossm-vs-community.adoc[Comparing Service Mesh and Istio]
**  [Service Mesh installation]
*** xref:service_mesh/service_mesh_install/preparing-ossm-installation.adoc[Preparing to install Service Mesh]
*** xref:service_mesh/service_mesh_install/installing-ossm.adoc[Installing Service Mesh]
*** xref:service_mesh/service_mesh_install/customizing-installation-ossm.adoc[Customizing the installation]
*** xref:service_mesh/service_mesh_install/updating-ossm.adoc[Updating Service Mesh]
*** xref:service_mesh/service_mesh_install/removing-ossm.adoc[Removing Service Mesh]
**  [Day Two]
*** xref:service_mesh/service_mesh_day_two/prepare-to-deploy-applications-ossm.adoc[Deploying applications on Service Mesh]
*** xref:service_mesh/service_mesh_day_two/configuring-jaeger.adoc[Configuring Jaeger]
*** xref:service_mesh/service_mesh_day_two/ossm-example-bookinfo.adoc[Example application]
*** xref:service_mesh/service_mesh_day_two/ossm-tutorial-jaeger-tracing.adoc[Distributed tracing tutorial]
*** xref:service_mesh/service_mesh_day_two/ossm-auto-route.adoc[Automatic route creation]
**  [Service Mesh user guide]
*** xref:service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc[Traffic management]
*** xref:service_mesh/service_mesh_user_guide/ossm-observability.adoc[Data visualization and observability]
*** xref:service_mesh/service_mesh_user_guide/ossm-security.adoc[Security]
**  [Support]
*** xref:service_mesh/service_mesh_support/ossm-collecting-ossm-data.adoc[Collecting Service Mesh data for support]
**  [3scale adapter]
*** xref:service_mesh/threescale_adapter/threescale-adapter.adoc[Using the 3scale Istio adapter]
*  Jaeger]
** xref:jaeger/rhbjaeger-release-notes.adoc[Jaeger release notes]
**  [Jaeger architecture]
*** xref:jaeger/jaeger_arch/rhbjaeger-architecture.adoc[Jaeger architecture]
**  [Jaeger installation]
*** xref:jaeger/jaeger_install/rhbjaeger-installation.adoc[Installing Jaeger]
*** xref:jaeger/jaeger_install/rhbjaeger-deploying.adoc[Deploying Jaeger]
*** xref:jaeger/jaeger_install/rhbjaeger-updating.adoc[Upgrading Jaeger]
*** xref:jaeger/jaeger_install/rhbjaeger-removing.adoc[Removing Jaeger]
*  Container-native virtualization]
** xref:cnv/cnv-about-cnv.adoc[About container-native virtualization]
** 
[Container-native virtualization release notes]
*** xref:cnv/cnv_release_notes/cnv-2-3-release-notes.adoc[Container-native virtualization release notes]
** 
[Container-native virtualization installation]
*** xref:cnv/cnv_install/preparing-cluster-for-cnv.adoc[Preparing your OpenShift cluster for container-native virtualization]
*** xref:cnv/cnv_install/installing-container-native-virtualization.adoc[Installing container-native virtualization]
*** xref:cnv/cnv_install/cnv-installing-virtctl.adoc[Installing the virtctl client]
*** xref:cnv/cnv_install/uninstalling-container-native-virtualization.adoc[Uninstalling container-native virtualization]
** xref:cnv/upgrading-container-native-virtualization.adoc[Upgrading container-native virtualization]
** xref:cnv/cnv-using-the-cli-tools.adoc[Using the CLI tools]
**  [Virtual machines]
*** xref:cnv/cnv_virtual_machines/cnv-create-vms.adoc[Creating virtual machines]
*** xref:cnv/cnv_virtual_machines/cnv-edit-vms.adoc[Editing virtual machines]
*** xref:cnv/cnv_virtual_machines/cnv-edit-boot-order.adoc[Editing boot order]
*** xref:cnv/cnv_virtual_machines/cnv-delete-vms.adoc[Deleting virtual machines]
*** xref:cnv/cnv_virtual_machines/cnv-deleting-vmis.adoc[Deleting virtual machine instances]
*** xref:cnv/cnv_virtual_machines/cnv-controlling-vm-states.adoc[Controlling virtual machine states]
*** xref:cnv/cnv_virtual_machines/cnv-accessing-vm-consoles.adoc[Accessing virtual machine consoles]
*** xref:cnv/cnv_virtual_machines/cnv-installing-virtio-drivers-on-existing-windows-vm.adoc[Installing VirtIO driver on an existing Windows virtual machine]
*** xref:cnv/cnv_virtual_machines/cnv-installing-virtio-drivers-on-new-windows-vm.adoc[Installing VirtIO driver on a new Windows virtual machine]
*** 
[Advanced virtual machine management]
**** xref:cnv/cnv_virtual_machines/cnv_advanced_vm_management/cnv-automating-management-tasks.adoc[Automating management tasks]
**** xref:cnv/cnv_virtual_machines/cnv_advanced_vm_management/cnv-configuring-pxe-booting.adoc[Configuring PXE booting for virtual machines]
**** xref:cnv/cnv_virtual_machines/cnv_advanced_vm_management/cnv-managing-guest-memory.adoc[Managing guest memory]
**** xref:cnv/cnv_virtual_machines/cnv_advanced_vm_management/cnv-dedicated-resources-vm.adoc[Enabling dedicated resources for a virtual machine]
*** 
[Importing virtual machines]
**** xref:cnv/cnv_virtual_machines/cnv_importing_vms/cnv-tls-certificates-for-dv-imports.adoc[TLS certificates for DataVolume imports]
**** xref:cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes.adoc[Importing virtual machine images with DataVolumes]
**** xref:cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes-block.adoc[Importing virtual machine images to block storage with DataVolumes]
**** xref:cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-vmware-vm.adoc[Importing a VMware virtual machine or template]
*** 
[Cloning virtual machines]
**** xref:cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-enabling-user-permissions-to-clone-datavolumes.adoc[Enabling user permissions to clone DataVolumes across namespaces]
**** xref:cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-cloning-vm-disk-into-new-datavolume.adoc[Cloning a virtual machine disk into a new DataVolume]
**** xref:cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-cloning-vm-using-datavolumetemplate.adoc[Cloning a virtual machine by using a DataVolumeTemplate]
**** xref:cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-cloning-vm-disk-into-new-datavolume-block.adoc[Cloning a virtual machine disk into a new block storage DataVolume]
*** 
[Virtual machine networking]
**** xref:cnv/cnv_virtual_machines/cnv_vm_networking/cnv-using-the-default-pod-network-with-cnv.adoc[Using the default Pod network with container-native virtualization]
**** xref:cnv/cnv_virtual_machines/cnv_vm_networking/cnv-attaching-vm-multiple-networks.adoc[Attaching a virtual machine to multiple networks]
**** xref:cnv/cnv_virtual_machines/cnv_vm_networking/cnv-installing-qemu-guest-agent.adoc[Installing the QEMU guest agent on virtual machines]
**** xref:cnv/cnv_virtual_machines/cnv_vm_networking/cnv-viewing-ip-of-vm-nic.adoc[Viewing the IP address of NICs on a virtual machine]
*** 
[Virtual machine disks]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-configuring-local-storage-for-vms.adoc[Configuring local storage for virtual machines]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-uploading-local-disk-images-virtctl.adoc[Uploading local disk images by using the virtctl tool]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-uploading-local-disk-images-block.adoc[Uploading a local disk image to a block storage DataVolume]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-moving-local-vm-disk-to-different-node.adoc[Moving a local virtual machine disk to a different node]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-expanding-virtual-storage-with-blank-disk-images.adoc[Expanding virtual storage by adding blank disk images]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-storage-defaults-for-datavolumes.adoc[Storage defaults for DataVolumes]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-preparing-cdi-scratch-space.adoc[Preparing CDI scratch space]
**** xref:cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-deleting-datavolumes.adoc[Deleting DataVolumes]
**  [Virtual machine templates]
*** xref:cnv/cnv_vm_templates/cnv-creating-vm-template.adoc[Creating virtual machine templates]
*** xref:cnv/cnv_vm_templates/cnv-editing-vm-template.adoc[Editing a virtual machine template]
*** xref:cnv/cnv_vm_templates/cnv-dedicated-resources-vm-template.adoc[Enabling dedicated resources for a virtual machine template]
*** xref:cnv/cnv_vm_templates/cnv-deleting-vm-template.adoc[Deleting a virtual machine template]
**  [Live migration]
*** xref:cnv/cnv_live_migration/cnv-live-migration.adoc[Virtual machine live migration]
*** xref:cnv/cnv_live_migration/cnv-live-migration-limits.adoc[Live migration limits and timeouts]
*** xref:cnv/cnv_live_migration/cnv-migrate-vmi.adoc[Migrating a virtual machine instance to another node]
*** xref:cnv/cnv_live_migration/cnv-monitor-vmi-migration.adoc[Monitoring live migration of a virtual machine instance]
*** xref:cnv/cnv_live_migration/cnv-cancel-vmi-migration.adoc[Cancelling the live migration of a virtual machine instance]
*** xref:cnv/cnv_live_migration/cnv-configuring-vmi-eviction-strategy.adoc[Configuring virtual machine eviction strategy]
**  [Node maintenance]
*** xref:cnv/cnv_node_maintenance/cnv-refresh-certificates.adoc[Manually refreshing TLS certificates]
*** xref:cnv/cnv_node_maintenance/cnv-node-maintenance.adoc[Node maintenance mode]
*** xref:cnv/cnv_node_maintenance/cnv-setting-node-maintenance.adoc[Setting a node to maintenance mode]
*** xref:cnv/cnv_node_maintenance/cnv-resuming-node.adoc[Resuming a node from maintenance mode]
**  [Node networking]
*** xref:cnv/cnv_node_network/cnv-observing-node-network-state.adoc[Observing node network state]
*** xref:cnv/cnv_node_network/cnv-updating-node-network-config.adoc[Updating node network configuration]
*** xref:cnv/cnv_node_network/cnv-troubleshooting-node-network.adoc[Troubleshooting node network configuration]
**  [Logging,
events, and monitoring]
*** xref:cnv/cnv_logging_events_monitoring/cnv-logs.adoc[Viewing logs]
*** xref:cnv/cnv_logging_events_monitoring/cnv-events.adoc[Viewing events]
*** xref:cnv/cnv_logging_events_monitoring/cnv-viewing-information-about-vm-workloads.adoc[Viewing information about virtual machine workloads]
*** xref:cnv/cnv_logging_events_monitoring/cnv-monitoring-vm-health.adoc[Monitoring virtual machine health]
*** xref:cnv/cnv_logging_events_monitoring/cnv-using-dashboard-to-get-cluster-info.adoc[Viewing cluster information]
*** xref:cnv/cnv_logging_events_monitoring/cnv-openshift-cluster-monitoring.adoc[OpenShift cluster monitoring, logging, and Telemetry]
*** xref:cnv/cnv_logging_events_monitoring/cnv-collecting-cnv-data.adoc[Collecting container-native virtualization data for Red Hat Support]
*  Serverless applications]
** xref:serverless/serverless-release-notes.adoc[Release Notes]
** xref:serverless/serverless-support.adoc[Support]
** xref:serverless/serverless-getting-started.adoc[Getting started with OpenShift Serverless]
**  [Installing OpenShift Serverless]
*** xref:serverless/installing_serverless/installing-openshift-serverless.adoc[Installing OpenShift Serverless]
*** xref:serverless/installing_serverless/installing-knative-serving.adoc[Installing Knative Serving]
*** xref:serverless/installing_serverless/installing-knative-eventing.adoc[Installing Knative Eventing]
*** xref:serverless/installing_serverless/serverless-install-config-options.adoc[Advanced installation configuration options]
*** xref:serverless/installing_serverless/upgrading-serverless.adoc[Upgrading the OpenShift Serverless Operator]
*** xref:serverless/installing_serverless/removing-openshift-serverless.adoc[Removing OpenShift Serverless]
*** xref:serverless/installing_serverless/installing-kn.adoc[Installing the Knative CLI]
** xref:serverless/serving-creating-managing-apps.adoc[Creating and managing serverless applications]
** xref:serverless/serverless-HA.adoc[High availability on OpenShift Serverless]
** xref:serverless/serverless-tracing.adoc[Tracing requests]
**  [Knative CLI]
*** xref:serverless/knative_cli/knative-cli.adoc[Getting started with Knative CLI]
**  [Knative Serving]
*** xref:serverless/knative_serving/serverless-knative-serving.adoc[How Knative Serving works]
*** xref:serverless/knative_serving/configuring-knative-serving-autoscaling.adoc[Configuring Knative Serving autoscaling]
*** xref:serverless/knative_serving/cluster-logging-serverless.adoc[Cluster logging with OpenShift Serverless]
*** xref:serverless/knative_serving/splitting-traffic-between-revisions.adoc[Splitting traffic between revisions]
**  [Knative Eventing]
*** xref:serverless/knative_eventing/serverless-knative-eventing.adoc[How Knative Eventing works]
*** xref:serverless/knative_eventing/serverless-kn-source.adoc[Using the kn CLI to list event sources and event source types]
*** xref:serverless/knative_eventing/serverless-apiserversource.adoc[Using ApiServerSource]
*** xref:serverless/knative_eventing/serverless-pingsource.adoc[Using PingSource]
*** xref:serverless/knative_eventing/serverless-sinkbinding.adoc[Using SinkBinding]
*** xref:serverless/knative_eventing/serverless-kn-trigger.adoc[Using triggers]
*** xref:serverless/knative_eventing/serverless-using-brokers.adoc[Using the broker]
*** xref:serverless/knative_eventing/serverless-channels.adoc[Using channels]
** xref:serverless/serverless-metering.adoc[Using metering with OpenShift Serverless]
